include ../../Makefile.bas
A=

##==============================================================================
BINPATH = -L$(SRC_ROOT)/../../../bin
INCPATH = -I$(SRC_ROOT)/../../../include 
LIBPATH = -L$(SRC_ROOT)/../../../lib 

TARG_BIN_PATH = $(SRC_ROOT)/../../../bin
TARG_LIB_PATH = $(SRC_ROOT)/../../../lib
TARG_INC_PATH = $(SRC_ROOT)/../../../include

OTHER_LIBS = -lASNet.$(ARCH).$(VERSION) 
TEST_SVR_TARG = Server.$(ARCH).$(VERSION)
TEST_SVR_OBJS = Server.o TCPServerSpi.o 
TEST_CLT_TARG = Client.$(ARCH).$(VERSION)
TEST_CLT_OBJS = Client.o TCPClientSpi.o 

$(TEST_SVR_TARG) : $(TEST_SVR_OBJS)
	$(A)$(ECHO) "Linking   [test] file:[$@] ..."
	$(A)$(CXX) $(CFLAGS) $(TEST_SVR_OBJS) $(INCPATH) $(BINPATH) $(OTHER_LIBS) $(LIBS) -o $(TARG_BIN_PATH)/$@
	$(A)$(RM) $(TEST_SVR_OBJS)

$(TEST_CLT_TARG) : $(TEST_CLT_OBJS)
	$(A)$(ECHO) "Linking   [test] file:[$@] ..."
	$(A)$(CXX) $(CFLAGS) $(TEST_CLT_OBJS) $(INCPATH) $(BINPATH) $(OTHER_LIBS) $(LIBS) -o $(TARG_BIN_PATH)/$@
	$(A)$(RM) $(TEST_SVR_OBJS)

##==============================================================================
