include Makefile.bas
A=

all:
	$(A)$(MAKE) -C MThread all
	$(A)$(MAKE) -C Net all

clean    :
	$(A)$(MAKE) -C MThread clean 
	$(A)$(MAKE) -C Net clean 

install  :
	$(A)$(MAKE) -C MThread install 
	$(A)$(MAKE) -C Net install 

##==============================================================================
